name: Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['lts/*']
        os: [ubuntu-latest]
    env:
      CI: 1 # prevents extra Cypress installation progress messages
      HUSKY: 0 # disables husky hooks
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: ${{ matrix.node }}

      - name: Verify
        run: make verify

      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: 'coverage/clover.xml'
          threshold_alert: 80
          threshold_warning: 90
